services:
  mysql:
    image: mysql:8
    container_name: teamtasks_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teamtasks
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - teamtasks_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: teamtasks_backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
      DB_HOST: 10.0.3.101
      DB_PORT: 3306
      DB_NAME: teamtasks
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: supersecret
    networks:
      - teamtasks_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: teamtasks_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - teamtasks_network

volumes:
  mysql_data:

networks:
  teamtasks_network:
    driver: bridge